{{- if and .Release.IsInstall .Values.database.createInstance }}
{{- if not .Values.database.secret.useExisting  }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: "{{ .Values.database.secret.name }}"
stringData:
  host: "{{ default ( include "semaphore.database.name" . ) .Values.database.config.host }}"
  port: "{{ default 5432 .Values.database.config.port }}"
  databaseName: "{{ .Values.database.config.databaseName }}"
  userName: "{{ include "semaphore.database.userName" . }}"
  userPassword: "{{ include "semaphore.database.userPassword" . }}"
{{- end }}
{{- end }}