{{- if and .Release.IsInstall .Values.database.createInstance }}
{{- if not .Values.database.secret.useExisting  }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: "{{ .Values.database.secret.name }}"
stringData:
  {{ .Values.database.secret.keys.host }}: "{{ default ( include "semaphore.database.name" . ) .Values.database.config.host }}"
  {{ .Values.database.secret.keys.port }}: "{{ default 5432 .Values.database.config.port }}"
  {{ .Values.database.secret.keys.databaseName }}: "{{ .Values.database.config.databaseName }}"
  {{ .Values.database.secret.keys.username }}: "{{ include "semaphore.database.userName" . }}"
  {{ .Values.database.secret.keys.password }}: "{{ include "semaphore.database.userPassword" . }}"
{{- end }}
{{- end }}
