{{- if .Values.database.createInstance }}
{{- if not .Values.database.secret.useExisting  }}

{{ $previousSecret := (lookup "v1" "Secret" ( include "semaphore.namespace" . ) .Values.database.secret.name ) | default dict }}
{{ $previousSecretData := (get $previousSecret "data") | default dict }}
{{ $previousUserPassword := (get $previousSecretData .Values.database.secret.keys.password) }}
{{ $userPassword := default ( randAlphaNum 32 ) $previousUserPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: "{{ .Values.database.secret.name }}"
stringData:
  {{ .Values.database.secret.keys.host }}: "{{ default ( include "semaphore.database.name" . ) .Values.database.config.host }}"
  {{ .Values.database.secret.keys.port }}: "{{ default 5432 .Values.database.config.port }}"
  {{ .Values.database.secret.keys.databaseName }}: "{{ default "semaphore" .Values.database.config.databaseName }}"
  {{ .Values.database.secret.keys.username }}: "{{ default "semaphore_user" .Values.database.config.userName }}"
  {{ .Values.database.secret.keys.password }}: "{{ default $userPassword .Values.database.config.userPassword }}"
{{- end }}
{{- end }}
