{{- if .Values.semaphore.ingress.enabled }}
---

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: "extensions/v1beta1"
{{- end }}
kind: Ingress
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "semaphore.name" .}}'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.componentName }}"
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "semaphore.label" .}}"
    {{- end }}
{{- if .Values.semaphore.ingress.labels }}
{{ toYaml .Values.semaphore.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.semaphore.ingress.annotations }}
  annotations:
{{ toYaml .Values.semaphore.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "semaphore.fullname" . }}
spec:
{{- if and .Values.semaphore.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.semaphore.ingress.ingressClassName | quote }}
{{- end }}
  rules:
  - http:
      paths:
      - backend:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "semaphore.service.name" . }}
            port:
              number: {{ .Values.semaphore.service.port }}
        pathType: "{{ default "Prefix" .Values.semaphore.ingress.pathType }}"
{{- else }}
          serviceName: {{ template "semaphore.fullname" . }}
          servicePort: {{ .Values.semaphore.service.port }}
{{- end }}
{{- if .Values.semaphore.ingress.path }}
        path: {{ .Values.semaphore.ingress.path }}
{{- end -}}
{{- if .Values.semaphore.ingress.hostName }}
    host: {{ .Values.semaphore.ingress.hostName | quote }}
{{- end }}
{{- if .Values.semaphore.ingress.tls }}
  tls:
{{ toYaml .Values.semaphore.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
