{{ if .Release.IsInstall }}
{{- if .Values.restore.enabled }}
{{- if and ( include "semaphore.restore.fromGcsStorage" . ) ( not .Values.restore.secret.useExisting ) }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ .Values.restore.secret.name }}
stringData:
  {{ .Values.restore.secret.keys.bucket }}: {{ .Values.restore.gcp.bucket }}
  {{ .Values.restore.secret.keys.bucketDirectory }}: {{ .Values.restore.gcp.bucketDirectory }}
  {{ .Values.restore.secret.keys.projectId }}: {{ .Values.restore.gcp.projectId }}
  {{ .Values.restore.secret.keys.serviceAccountEmail }}: {{ .Values.restore.gcp.serviceAccountEmail }}
  {{ .Values.restore.secret.keys.keyJson }}: {{ toJson .Values.restore.gcp.keyJson }}

{{- end }}
{{- end }}
{{- end }}


{{- if .Release.IsInstall }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ include "semaphore.config.configMapName" . }}
stringData:
  config.json: |-
    {
      "postgres": {
        "host": "##HOST##",
        "name": "##DATABASE_NAME##",
        "user": "##USER_NAME##",
        "pass": "##USER_PASSWORD##",
        "options": null
      },
      "dialect": "postgres",
      "web_host": "{{ .Values.semaphore.config.web_host }}",
      "port": "{{ default 3000 .Values.semaphore.containerPort | int }}",
      "interface": "",
      "tmp_path": "/home/semaphore/tmp",
      "cookie_hash": "{{ randAlphaNum 32 | b64enc }}",
      "cookie_encryption": "{{ randAlphaNum 32 | b64enc }}",
      "access_key_encryption": "{{ randAlphaNum 32 | b64enc }}",
      "email_secure": false,
      "email_alert": {{ default false .Values.semaphore.config.email_alert }},
      "email_host": "{{ default "" .Values.semaphore.config.email_host }}",
      "email_port": "{{ default "" (.Values.semaphore.config.email_port | int) }}",
      "email_username": "{{ default "" .Values.semaphore.config.email_username }}",
      "email_password": "{{ default "" .Values.semaphore.config.email_userpassword}}",
      "email_sender": "{{ default "" .Values.semaphore.config.email_sender }}",
      "ldap_enable": false,
      "ldap_needtls": false,
      "ldap_binddn": "",
      "ldap_bindpassword": "",
      "ldap_server": "",
      "ldap_searchdn": "",
      "ldap_searchfilter": "",
      "ldap_mappings": {
        "dn": "",
        "mail": "",
        "uid": "",
        "cn": ""
      },
      "telegram_chat": "",
      "telegram_token": "",
      "concurrency_mode": "",
      "max_parallel_tasks": 0,
      "telegram_alert": false,
      "ssh_config_path": "",
      "variables_passing_method": ""
    }
{{- end}}