---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ include "semaphore.service.name" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.semaphore.service.type }}
  selector:
    {{- include "semaphore.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ default 3000 .Values.semaphore.service.port | int }}
      targetPort: {{ default 3000 .Values.semaphore.containerPort | int }}
      protocol: TCP
      name: http
