---

{{ $dbCertificateDir := "/var/lib/postgresql/database-certificates" }}
{{ $dbCertificateFilename := "postgres" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ include "semaphore.name" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "semaphore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "semaphore.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- if or .Values.database.enabled (include "semaphore.restore.fromGcsStorage" . ) }}
      initContainers:
        {{- if include "semaphore.restore.fromGcsStorage" . }}
        - name: download-database-dump-file
          image: "{{ .Values.restore.image.name }}:{{ .Values.restore.image.tag }}"
          imagePullPolicy: Always
          command: [ 'bash', '-c' ]
          args:
            - set -xuv;
              filename="/{{ .Values.restore.baseFilename }}.tar.gz";
              file="/tmp/dump${filename}"
              gcloud auth activate-service-account "${GCS_SERVICE_ACCOUNT_EMAIL}" --key-file=/tmp/key.json --project="${GCS_PROJECT_ID}";
              gsutil cp "gs://${GCS_BUCKET}${GCS_BUCKET_DIRECTORY}${filename}" "${file}"
          env:
            - name: GCS_SERVICE_ACCOUNT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-restore-gcp
                  key: serviceAccountEmail
            - name: GCS_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-restore-gcp
                  key: projectId
            - name: GCS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-restore-gcp
                  key: bucket
            - name: GCS_BUCKET_DIRECTORY
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-restore-gcp
                  key: bucketDirectory
          volumeMounts:
            - mountPath: /tmp/dump
              name: shared-database-restore-directory
            - name: gcp-restore-key-volume
              mountPath: /tmp/key.json
              subPath: keyJson
        - name: restore-database-from-dump-file
          image: "{{ .Values.database.image.name }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: Always
          command: [ 'sh', '-c' ]
          args:
            - set -exuv;
              echo "${POSTGRES_HOST}:${POSTGRES_PORT}:${POSTGRES_DATABASE}:${POSTGRES_USER}:${POSTGRES_PASSWORD}" > "$HOME/.pgpass";
              chmod 600 "$HOME/.pgpass";
              - while ! nc -w 1 "${POSTGRES_HOST}" "${POSTGRES_PORT}" ; do echo "waiting for database"; sleep 1; done;
              cd /tmp/dump;
              tar zxvf "{{ .Values.restore.baseFilename }}.tar.gz";
              pg_restore -U "${POSTGRES_USER} "{{- include "semaphore.backup.postgres.extraOptions" . }}" -d "${POSTGRES_DATABASE} < "{{ .Values.restore.baseFilename }}.sql"
          env:
            - name: POSTGRES_HOST
              value: "{{- include "semaphore.service.name" . }}"
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: port
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: databaseName
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: userName
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: userPassword
          volumeMounts:
            - mountPath: /tmp/dump
              name: shared-database-restore-directory
        {{- end }}
        {{- if .Values.database.enabled }}
        - name: database-certificate-creation
          image: alpine:latest
          imagePullPolicy: Always
          command: [ 'sh', '-c' ]
          args:
            - apk update;
              apk add openssl;
              openssl genrsa -out {{ $dbCertificateFilename }}.key 4096;
              openssl req -new -key {{ $dbCertificateFilename }}.key -out {{ $dbCertificateFilename }}.csr -subj "/C=/ST=/L=/O=/CN=semaphore.local";
              openssl x509 -req -days 3650 -in {{ $dbCertificateFilename }}.csr -signkey {{ $dbCertificateFilename }}.key -out {{ $dbCertificateFilename }}.crt;
              mv postgres.* {{ $dbCertificateDir }};
              chmod -R 600 {{ $dbCertificateDir }}/{{ $dbCertificateFilename }}.key;
              chmod -R 640 {{ $dbCertificateDir }}/{{ $dbCertificateFilename }}.csr;
              chmod -R 640 {{ $dbCertificateDir }}/{{ $dbCertificateFilename }}.crt;
              chown -R "{{ .Values.database.permissions.userId }}":"{{ .Values.database.permissions.groupId }}" {{ $dbCertificateDir }}
          volumeMounts:
            - mountPath: {{ $dbCertificateDir }}
              name: database-certificates-volume
        {{- end }}
      {{- end }}
      containers:
        - name: "semaphore"
          image: "{{ .Values.semaphore.image.name }}:{{ .Values.semaphore.image.tag }}"
          imagePullPolicy: "{{ .Values.semaphore.imagePullPolicy }}"
          command: [ 'sh', '-c' ]
          args:
            - while ! nc -w 1 "{{- include "semaphore.database.host" . }}" "{{- include "semaphore.database.port" . }}" ; do echo "waiting for database"; sleep 1; done;
              semaphore service
          ports:
            - containerPort: {{ default 3000 .Values.semaphore.containerPort | int}}
          volumeMounts:
            - mountPath: /home/semaphore/config.json
              name: semaphore-configuration
              subPath: config.json
              readOnly: true
          readinessProbe:
            httpGet:
              port: {{ default 3000 .Values.semaphore.containerPort | int }}
              path: /ping
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: {{ default 3000 .Values.semaphore.containerPort | int }}
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
        {{- if .Values.database.enabled }}
        - name: "semaphore-database"
          image: "{{ .Values.database.image.name }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: "{{ .Values.database.imagePullPolicy }}"
          args: [ '-c', 'ssl=on', '-c', 'ssl_cert_file={{ $dbCertificateDir }}/{{ $dbCertificateFilename }}.crt', '-c', 'ssl_key_file={{ $dbCertificateDir }}/{{ $dbCertificateFilename }}.key' ]
          ports:
            - containerPort: {{ default 5432 .Values.database.containerPort | int }}
          volumeMounts:
            {{- if .Values.existingSecretSSHDir }}
            - name: ssh-keys
              readOnly: true
              mountPath: "/home/semaphore/.ssh/"
            {{- end }}
            {{- if .Values.database.persistenceEnabled }}
            - mountPath: /var/lib/postgresql/data
              name: semaphore-database-volume-storage
              subPath: postgres
            {{- end }}
            - mountPath: {{ $dbCertificateDir }}
              name: database-certificates-volume
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: databaseName
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: userName
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semaphore-database-secrets
                  key: userPassword
                  optional: false
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 3
            tcpSocket:
              port: {{ default 5432 .Values.database.containerPort | int }}
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            tcpSocket:
              port: {{ default 5432 .Values.database.containerPort | int }}
        {{- end}}
      volumes:
        - name: semaphore-configuration
          secret:
            secretName: "{{ include "semaphore.config.secretName" . }}"
        {{- if .Values.existingSecretSSHDir }}
        - name: ssh-keys
          secret:
            secretName: {{ .Values.existingSecretSSHDir }}
        {{- end }}
        {{- if .Values.database.enabled }}
        - name: database-certificates-volume
          emptyDir: { }
        {{- if .Values.database.persistenceEnabled }}
        - name: semaphore-database-volume-storage
          persistentVolumeClaim:
            claimName: {{ include "semaphore.database.volume.name" . }}
        {{- end }}
        {{- end }}
        {{- if .Values.restore.enabled }}
        - name: shared-database-restore-directory
          emptyDir: { }
        {{- end }}
        {{- if include "semaphore.restore.fromGcsStorage" . }}
        - name: gcp-restore-key-volume
          secret:
            secretName: semaphore-database-restore-gcp
            items:
              - key: keyJson
                path: key.json
        {{- end }}
