{{/*
Secrets are merged to single file due to limitation of generating value once and using it in multiple template files
see link: https://github.com/helm/helm/issues/6456
*/}}

{{ $generatedPassword := randAlphaNum 64}}
{{ $databasePassword := default $generatedPassword .Values.database.config.userPassword }}

{{ if .Release.IsInstall }}
---

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ include "semaphore.config.secretName" . }}
type: Opaque
stringData:
  config.json: |-
    {
      "postgres": {
        "host": "{{ include "semaphore.database.host" . }}:{{ include "semaphore.database.port" . | int }}",
        "name": "{{ include "semaphore.database.name" . }}",
        "user": "{{ include "semaphore.database.userName" . }}",
        "pass": "{{ $databasePassword }}",
        "options": null
      },
      "dialect": "postgres",
      "web_host": "{{ .Values.config.web_host }}",
      "port": "{{ default 3000 .Values.semaphore.containerPort | int }}",
      "interface": "",
      "tmp_path": "/home/semaphore/tmp",
      "cookie_hash": "{{ randAlphaNum 32 | b64enc }}",
      "cookie_encryption": "{{ randAlphaNum 32 | b64enc }}",
      "access_key_encryption": "{{ randAlphaNum 32 | b64enc }}",
      "email_secure": false,
      "email_alert": {{ default false .Values.config.email_alert }},
      "email_host": "{{ default "" .Values.config.email_host }}",
      "email_port": "{{ default "" (.Values.config.email_port | int) }}",
      "email_username": "{{ default "" .Values.config.email_username }}",
      "email_password": "{{ default "" .Values.config.email_password}}",
      "email_sender": "{{ default "" .Values.config.email_sender }}",
      "ldap_enable": false,
      "ldap_needtls": false,
      "ldap_binddn": "",
      "ldap_bindpassword": "",
      "ldap_server": "",
      "ldap_searchdn": "",
      "ldap_searchfilter": "",
      "ldap_mappings": {
        "dn": "",
        "mail": "",
        "uid": "",
        "cn": ""
      },
      "telegram_chat": "",
      "telegram_token": "",
      "concurrency_mode": "",
      "max_parallel_tasks": 0,
      "telegram_alert": false,
      "ssh_config_path": "",
      "variables_passing_method": ""
    }
{{- end }}


{{ if .Release.IsInstall }}
{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: semaphore-database-secrets
stringData:
  host: "{{ include "semaphore.database.host" . }}"
  port: "{{ include "semaphore.database.port" . }}"
  databaseName: "{{ include "semaphore.database.name" . }}"
  userName: "{{ include "semaphore.database.userName" . }}"
  userPassword: "{{ $databasePassword }}"
{{- end }}
{{- end }}


{{ if .Release.IsInstall }}
{{- if .Values.backup.enabled }}
{{- if include "semaphore.backup.toGcsStorage" . }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: semaphore-database-backup-gcp
stringData:
  bucket: {{ .Values.backup.gcp.bucket }}
  bucketDirectory: {{ .Values.backup.gcp.bucketDirectory }}
  projectId: {{ .Values.backup.gcp.projectId }}
  serviceAccountEmail: {{ .Values.backup.gcp.serviceAccountEmail }}
  keyJson: {{ .Values.backup.gcp.keyJson | quote }}
{{- end }}
{{- end }}
{{- end }}

{{ if .Release.IsInstall }}
{{- if .Values.restore.enabled }}
{{- if include "semaphore.restore.fromGcsStorage" . }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: semaphore-database-restore-gcp
stringData:
  bucket: {{ .Values.restore.gcp.bucket }}
  bucketDirectory: {{ .Values.restore.gcp.bucketDirectory }}
  projectId: {{ .Values.restore.gcp.projectId }}
  serviceAccountEmail: {{ .Values.restore.gcp.serviceAccountEmail }}
  keyJson: {{ .Values.restore.gcp.keyJson | quote }}
{{- end }}
{{- end }}
{{- end }}