---

fullnameOverride: ""
nameOverride: ""
namespaceOverride: ""
chartNameOverride: ""

semaphore:
  image:
    name: "ansiblesemaphore/semaphore"
    tag: "v2.8.22"
  imagePullPolicy: "IfNotPresent"
  containerPort: 3000

# created as: https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys
existingSecretSSHDir: ""

config:
  web_host: ""
  email_alert: false
  email_host: ""
  email_port: ""
  email_username: ""
  email_userpassword: ""
  email_sender: ""

service:
  enabled: true
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  labels: {}
  annotations: {}
  ingressClassName: nginx
  path: "/"
  hostName: "semaphore.example.com"
  tls:
    # - secretName: semaphore.example.com
    #   hosts:
    #     - semaphore.example.com

database:
  enabled: true
  image:
    name: "postgres"
    tag: "14-alpine"
  imagePullPolicy: "IfNotPresent"
  volumeSize: 10Gi
  containerPort: 5432
  persistenceEnabled: true
  persistentVolumeClaimNameOverride: ""
  permissions:
    userId: 70
    groupId: 70
  config:
    host: "localhost"
    port: 5432
    databaseName: "semaphore"
    userName: ""
    userPassword: ""

restore:
  enabled: false
  image:
    name: "google/cloud-sdk"
    tag: "slim"
  # file name without extension located on gcs_storage/bucket/directory
  baseFilename: "database-dump"
  gcp:
    projectId: ""
    keyJson: "{}"
    serviceAccountEmail: ""
    bucket: ""
    bucketDirectory: ""

backup:
  enabled: false
  schedule: ""
  activeDeadlineSeconds: ""
  image:
    name: "google/cloud-sdk"
    tag: "slim"
  gcp:
    projectId: ""
    keyJson: "{}"
    serviceAccountEmail: ""
    bucket: ""
    bucketDirectory: ""
  postgresql:
    extraOptions: ""
