{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ include "semaphore.service.name" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "semaphore.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ default 3000 .Values.service.port | int }}
      targetPort: {{ default 3000 .Values.semaphore.containerPort | int }}
      protocol: TCP
      name: http
    {{- if .Values.database.enabled }}
    {{- if .Values.backup.enabled }}
    - port: {{ include "semaphore.database.port" | int }}
      targetPort: {{ default 5432 .Values.database.containerPort | int }}
      protocol: TCP
      name: database
    {{- end }}
    {{- end }}
{{- end }}
