{{ if and .Release.IsInstall ( include "semaphore.backup.toGcsStorage" . )}}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ .Values.backup.secret.name }}
stringData:
  bucket: {{ .Values.backup.gcp.bucket }}
  bucketDirectory: {{ .Values.backup.gcp.bucketDirectory }}
  projectId: {{ .Values.backup.gcp.projectId }}
  serviceAccountEmail: {{ .Values.backup.gcp.serviceAccountEmail }}
  keyJson: {{ toJson .Values.backup.gcp.keyJson }}
{{- end }}
