{{ if and .Release.IsInstall ( include "semaphore.backup.toGcsStorage" . )}}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "semaphore.namespace" . }}
  name: {{ .Values.backup.secret.name }}
stringData:
  {{ .Values.backup.secret.keys.bucket }}: {{ .Values.backup.gcp.bucket }}
  {{ .Values.backup.secret.keys.bucketDirectory }}: {{ .Values.backup.gcp.bucketDirectory }}
  {{ .Values.backup.secret.keys.projectId }}: {{ .Values.backup.gcp.projectId }}
  {{ .Values.backup.secret.keys.serviceAccountEmail }}: {{ .Values.backup.gcp.serviceAccountEmail }}
  {{ .Values.backup.secret.keys.keyJson }}: {{ toJson .Values.backup.gcp.keyJson }}
{{- end }}
